from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

expenses = [
    # FOOD
    ("rice", "food"),
    ("beans", "food"),
    ("jollof rice", "food"),
    ("jollof", "food"),
    ("fufu", "food"),
    ("bread", "food"),
    ("chicken", "food"),
    ("fish", "food"),
    ("yam", "food"),
    ("spaghetti", "food"),
    ("amala", "food"),
    ("eba", "food"),
    ("garri", "food"),
    ("pasta", "food"),
    ("noodles", "food"),
    ("breakfast", "food"),
    ("lunch", "food"),
    ("dinner", "food"),
    ("snacks", "food"),
    ("restaurant", "food"),
    ("bought rice", "food"),
    ("bought beans", "food"),
    ("bought jollof for lunch", "food"),
    ("ate jollof rice", "food"),
    ("bought food for dinner", "food"),
    ("bought chicken for dinner", "food"),
    ("bought bread for breakfast", "food"),
    ("bought noodles", "food"),
    ("ordered food", "food"),
    ("paid for lunch", "food"),

    # TRANSPORT
    ("bus", "transport"),
    ("bike", "transport"),
    ("uber", "transport"),
    ("uber ride", "transport"),
    ("bolt", "transport"),
    ("bolt ride", "transport"),
    ("taxi", "transport"),
    ("fuel", "transport"),
    ("petrol", "transport"),
    ("transport fare", "transport"),
    ("bus fare", "transport"),
    ("motorcycle", "transport"),
    ("paid for uber", "transport"),
    ("took an uber", "transport"),
    ("uber to school", "transport"),
    ("paid bus fare", "transport"),
    ("took a bus", "transport"),
    ("paid for fuel", "transport"),
    ("bought petrol", "transport"),
    ("bike ride", "transport"),
    ("taxi to work", "transport"),

    # CLOTHING
    ("shirt", "clothing"),
    ("trousers", "clothing"),
    ("dress", "clothing"),
    ("fabric", "clothing"),
    ("shoes", "clothing"),
    ("sneakers", "clothing"),
    ("skirt", "clothing"),
    ("clothes", "clothing"),
    ("clothing", "clothing"),
    ("blouse", "clothing"),
    ("top", "clothing"),
    ("jacket", "clothing"),
    ("jeans", "clothing"),
    ("shorts", "clothing"),
    ("sandal", "clothing"),
    ("bought a skirt", "clothing"),
    ("bought a new skirt", "clothing"),
    ("bought a shirt", "clothing"),
    ("bought new clothes", "clothing"),
    ("bought a dress", "clothing"),
    ("bought trousers", "clothing"),
    ("bought new shoes", "clothing"),
    ("bought a blouse", "clothing"),

    # EDUCATION
    ("school fees", "education"),
    ("school fee", "education"),
    ("textbook", "education"),
    ("textbooks", "education"),
    ("course", "education"),
    ("exam fee", "education"),
    ("tuition", "education"),
    ("school", "education"),
    ("lecture", "education"),
    ("assignment", "education"),
    ("paid school fees", "education"),
    ("paid my school fees", "education"),
    ("bought a textbook", "education"),
    ("paid exam fee", "education"),
    ("paid tuition", "education"),
    ("bought a course", "education"),
    ("paid for my course", "education"),
    ("book", "education"),
    ("books", "education"),
    ("bought a book", "education"),
    ("bought books", "education"),
    ("bought a school book", "education"),
    ("bought a study book", "education"),
    ("bought a textbook", "education"),
    ("bought textbooks", "education"),
    ("new book", "education"),
    ("school book", "education"),

    # AIRTIME / DATA
    ("mtn airtime", "airtime"),
    ("airtel airtime", "airtime"),
    ("glo airtime", "airtime"),
    ("9mobile airtime", "airtime"),
    ("bought airtime", "airtime"),
    ("bought mtn airtime", "airtime"),
    ("bought airtel airtime", "airtime"),
    ("recharged my phone", "airtime"),
    ("phone recharge", "airtime"),
    ("recharged my line", "airtime"),
    ("airtime recharge", "airtime"),
    ("bought data", "airtime"),
    ("bought internet data", "airtime"),
    ("bought mobile data", "airtime"),
    ("bought mtn data", "airtime"),
    ("bought airtel data", "airtime"),
    ("bought glo data", "airtime"),
    ("paid for internet", "airtime"),
    ("internet subscription", "airtime"),
    ("data subscription", "airtime"),
    ("internet data", "airtime"),
    ("mobile data", "airtime"),
    ("data bundle", "airtime"),

    # GIVING
    ("offering", "giving"),
    ("church offering", "giving"),
    ("gave offering", "giving"),
    ("paid offering", "giving"),
    ("donation", "giving"),
    ("made a donation", "giving"),
    ("gave a donation", "giving"),
    ("donated money", "giving"),
    ("gave money to charity", "giving"),
    ("charity donation", "giving"),
    ("charity", "giving"),
    ("gave money to church", "giving"),
    ("church donation", "giving"),
    ("church giving", "giving"),
    ("financial gift", "giving"),
    ("gave a financial gift", "giving"),
    ("gave someone money", "giving"),
    ("gift", "giving"),
    ("gave a gift", "giving"),
    ("donate", "giving"),
    ("donated", "giving"),
    ("giving", "giving"),
]
# Prepare training data
texts = [item[0] for item in expenses]
categories = [item[1] for item in expenses]
# Convert words into numbers
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)
# Train the machine learning model
model = LogisticRegression()
model.fit(X, categories)

# Function to predict a category
def predict_category(expense_name):
    expense_vector = vectorizer.transform([expense_name])
    prediction = model.predict(expense_vector)

    return prediction[0]